# Generated by Django 5.0.3 on 2024-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_shopit_img_alter_shopit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopit',
            name='description',
            field=models.CharField(default='This product does not have a description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopit',
            name='img',
            field=models.ImageField(upload_to='Uploaded/'),
        ),
    ]
