# Generated by Django 5.0.3 on 2024-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shopit_description_alter_shopit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopit',
            name='description',
            field=models.CharField(default='This product does not have a description.', max_length=2083),
        ),
    ]
